# Generated by Django 3.1.7 on 2021-05-26 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_is_private'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_private',
        ),
        migrations.AddField(
            model_name='user',
            name='is_cert_email',
            field=models.BooleanField(default=False),
        ),
    ]
